/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "adc.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#define ADC_MAX_VALUE 4095
//#define REFERENCE_VOLTAGE 3300 // Example 3.3V reference

/*20mg/100ml means 200 ppm alcohol concentration if ppm is greather then 200 then alcohole is ditected
Value -->0-299 --->Normal
Value -->300-400 --->Mild Alcoholic
Value -->More than 400
*/

int main(void) {
	UartInit(9600);
//	UartPuts("ADC Demo\r\n");
	//float input_voltage = 0.0;

	AdcInit();
	while(1) {
		char str[50];
		uint16_t val = AdcRead();
	//	sprintf(str, "ADC=%d\r\n", val);

		//input_voltage = ( (float)adc_reading / ADC_MAX_VALUE ) * REFERENCE_VOLTAGE;
	//	uint16_t input_voltage = (val/ ADC_MAX_VALUE ) * REFERENCE_VOLTAGE;
		uint16_t input_voltage  = (val * 3300) / 4095;
        if(input_voltage < 2000){
    		sprintf(str, "STATUS: Normal= %d\r\n", input_voltage);
        }
        else{
        	sprintf(str, "Alcohole is ditected = %d\r\n", input_voltage);
        }

		UartPuts(str);
		DelayMs(1000);
	}
}


